name: Generate and Publish

on:
  push:
    branches:
      - master

env:
  SSH_CREDENTIALS: ${{ secrets.SSH_CREDENTIALS }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cheking out the project
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
          extended: true

      - name: Build
        run: hugo --buildFuture --environment giv-cpsc

      # - name: Deploy with Rsync
      #   uses: burnett01/rsync-deployments@5.2
      #   with:
      #     switches: -anvzr --delete
      #     path: giv-public/
      #     remote_path: public_html/
      #     remote_host: giv.cpsc.ucalgary.ca
      #     remote_user: giv
      #     remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Depoly via SCP
        uses: appleboy/scp-action@master
        with:
          host: giv.cpsc.ucalgary.ca
          username: giv
          password: ${{ secrets.SSH_CREDENTIALS }}
          source: "giv-public/*"
          target: "public_html"
          use_insecure_cipher: true

      # - name: Depoloy
      #   run: bash deploy.sh

      # - name: Deploy via FTP
      #   uses: SamKirkland/FTP-Deploy-Action@4.2.0
      #   with:
      #     server: ftp.giv.cpsc.ucalgary.ca
      #     username: deploy@giv.cpsc.ucalgary.ca
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: "giv-public/"
      #     server-dir: "./"
      #     dry-run: true